### ISSUE TITLE
bug: httpx client requests result in `ssl.SSLCertVerificationError`

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla#1885]
**Describe the bug**
I tried connect to my deployed redcross environment via the Python client, but this result in an SSL error even though the environment is available via the browser.

**To Reproduce**
Use `rg.init(ai_url="my_environment_url", api_key="my_secret_key")`

**Expected behavior**
A decent connection.

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MaxOs
 - Browser [e.g. chrome, safari]: N.A.
 - Argilla Version [e.g. 1.0.0]: 1.0.1.
 - ElasticSearch Version [e.g. 7.10.2]: 7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.0.1

**Additional context**
```
Traceback (most recent call last):
  File "/Users/davidberenstein/Documents/programming/playground/red_cross/test.py", line 28, in <module>
    rg.log(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 657, in wrapped_func
    return func(*args, **kwargs)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 696, in log
    return active_api().log(*args, **kwargs)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 299, in log
    return future.result()
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 99, in __log_internal__
    raise ex
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 93, in __log_internal__
    return await api.log_async(*args, **kwargs)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/api.py", line 384, in log_async
    response = await async_bulk(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/argilla/client/sdk/commons/api.py", line 94, in async_bulk
    response = await async_client.post(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/Users/davidberenstein/Library/Caches/pypoetry/virtualenvs/playground-_S1_Uv85-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'redcross_104616782.argilla.io'. (_ssl.c:997)
```

**Comment by dvsrepo** [comment]
Hi @davidberenstein1957 I'd prefer to move this to the Team repo until it's clear this is a bug or it's related to the specific cloud environment for this project.
